#+TITLE: Packages Document Drafts

#+TODO: TODO(t) (e) DOIN(d) PEND(p) OUTL(o) EXPL(x) FDBK(b) WAIT(w) NEXT(n) IDEA(i) | ABRT(a) PRTL(r) RVIW(v) DONE(f)
#+OPTIONS: title:nil tags:nil todo:nil ^:nil f:t num:t pri:nil toc:t
#+LATEX_HEADER: \renewcommand\maketitle{} \usepackage[scaled]{helvet} \renewcommand\familydefault{\sfdefault}
#+FILETAGS: :DOC:DRAFT:PACKAGES:
#+HTML:<details>

* Document Drafts :DOC:DRAFT:PACKAGES:META:
#+HTML:</details>

#+NAME:Warning Message
#+BEGIN_QUOTE
[!WARNING]
Draft items are subjected to change and refile!
#+END_QUOTE
** OUTL Fzf Scripting :SCRIPTING:FZF:
:PROPERTIES:
:ID:       0635a10c-d33b-457f-b2eb-8d91480684bd
:END:
/Scripting with fzf/
*Checkout:*
+ [[https://seb.jambor.dev/posts/improving-shell-workflows-with-fzf/https://seb.jambor.dev/posts/improving-shell-workflows-with-fzf/][Improving workflow with fzf @Blog]]
+ [[https://github.com/beauwilliams/awesome-fzf][A semi-complete List of Fzf @Github]]
** OUTL Git Revert a pushed commit
DEADLINE: <2025-11-27 Thu>
/How to revert a pushed commit on public or private branch/
- *Visit:* [[https://www.youtube.com/watch?v=H2DuJNWbqLw][How to revert a pushed commit @Youtube]]
- *Goes-to:* [[id:0d065ce6-e02a-4dce-b7a5-29a1910d0e9c][Make Changes to Submodules @Org]]
** OUTL Command Multiple Git Repositories :GIT:
DEADLINE: <2025-11-27 Thu>
/Run git commands in parallel in multiple repositories/
- *Goes-to:* [[id:0d065ce6-e02a-4dce-b7a5-29a1910d0e9c][Make Changes to Submodules @Org]]
** DONE Initiate tmux on Homelab :SERVER:TMUX:SSH:
CLOSED: [2025-10-23 Thu 02:01] DEADLINE: <2025-10-23 Thu>
:PROPERTIES:
:ID:       36fece3a-2c38-48ec-bc23-73f11ddb5e13
:END:
To achieve seamless workflow between multiple devices, use =tmux= to attach to currently running =tmux-session= on =homelab=. To achieve this there are a few problems to look out for.
- *SSH* =RemoteCommand= does not launch terminal through a login shell and thus does not play well with =nerdfont= which depends on =varibales= on log
- *SSH* =RemoteCommand= and =ExecuteCommand= do not come hand in hand. Therefore, set =option= on run
- *Tmux* syntax =commands= are read in =whole string= this means in order to create script for =tmux= one must use layers of =substrings= in the script
  
#+NAME: Working command
#+BEGIN_SRC bash
ssh homelab -o RemoteCommand=none "exec $SHELL -lc 'tmux new -A -s 1'"
#+END_SRC

#+NAME: qtile keybind script
#+BEGIN_SRC python
def ssh_session(session_range):
    session_bind = []
    for i in session_range:
        session_bind.append(
            [
                str(i),
                f"kitty -e ssh homelab -o RemoteCommand=none \"exec $SHELL -lc 'tmux new -A -s {i}'\"",
                "pad_large",
            ]
        )
    return session_bind
#+END_SRC
** OUTL Reverse Tunneling :PROTOCOL:SSH:reversetunneling:
DEADLINE: <2025-11-27 Thu>
- Summary:
  + Reverse =ssh-tunneling= is useful when you need to connect to a remote computer that is hard to reach dir to =firewall= or complex network configurations
  + Reverse =ssh-tunneling= allows you to establish a new connection from your =local= computer back to the =remote= computer using the existing connection
  + Set up =ssh-keys= to make it more convenient to connect from the =remote= computer tho the local computer without being challenged for a =password=
#+html:<details><summary>Reverse ssh graph</summary>
#+BEGIN_SRC plain
                                                                    +-------------------+
                                                                    |  Local Machine    |
                                                                    | (Your Computer)   |
                                                                    |                   |
  Any SSH Client                                                    | +---------------+ |
        |                                                           | | SSH Server    | |
        |                                                           | | (Port 22)     | |
        |                                                           | +---------------+ |
        |                                                           +--------^----------+
        |                                                                    |
        | 1. Connects to remote server's port 2200                           | 4. The SSH client on your
        |    (e.g., ssh user@remote-ip -p 2200)                              |    local machine forwards the
        v                                                                    |    connection to its own
+---------------------------+                                                |    localhost:22.
|      Remote Server        |                                                |
|    (Remote Server IP)     |      2. SSH Tunnel established by your command |
|                           | <--------------------------------------------> |
| +-----------------------+ |                                                |
| | SSHD listens on 2200  | |         3. Traffic arriving on port 2200 is    |
| +-----------------------+ |            sent back through the tunnel.       |
|                           | ---------------------------------------------> |
+---------------------------+
#+END_SRC
#+html:</details>
- *Visit:* [[https://stackoverflow.com/a/76549625/25585364][Auto restart background ssh tunnel @Overflow]]
*** What is Reverse SSH Tunneling?
#+BEGIN_QUOTE
Reverse SSH Tunneling allows user to use that established connection to set up a new connect from a =local= computer back to the =remote= computer
#+END_QUOTE
Because the original connection came from the remote computer to you, using it to go in the other direction using it /in reverse/. Thus the name =reverse ssh tunneling=

*** How does SSH Tunneling Work?
- Reverse SSH Tunneling relies on the remote computer to take advantage of an already established connection to listen for a new connection request from the =local= computer
- The =remote= computer listens on a network port on the =local= computer. If it detects an =ssh= request on that port, it relays the connection request back to itself /or another device/ down the established connection. This provides a new connection from the =local= computer to the =remote= computer
*** Using SSH Reverse Tunneling
To establish a connection between the =remote= and =local= machine run:
#+BEGIN_SRC sh
ssh -o ControlMaster=auto -o ControlPath=/tmp/ssh-tunnel.socket -NR 2200:localhost:22 user@remote-ip
#+END_SRC
** OUTL Git Rebase vs Merge :GIT:
/Difference between git rebasing and merging/ \\
/*checkout:*/ [[https://www.geeksforgeeks.org/git/git-difference-between-merging-and-rebasing/][Git rebasing vs merging @G4g]]
** OUTL Ntfy Notifications :NTFY:NOTIFICATION:notificationsync:
/Self host and run ntfy server/
*** OUTL Running ntfy On Archlinux :ARCH:
/How to receive =ntfy-notification= on =archlinux=/ \\
/*Check-out:*/ [[https://github.com/ronilaukkarinen/ntfy-linux-receiver-service/][ntfy-listener systemd service @Github]]
** OUTL Pull ntfy notifications :NTFY:notificationsync:
DEADLINE: <2025-11-27 Thu>
- *OBJECTIVE:* Pull =ntfy= notifications when system connection went down
- *Check-out:* [[id:b6113f7d-9ec6-49df-80ff-2c0d7546475f][Run Service on Network Change @Org]]
- *Reference:* [[https://docs.ntfy.sh/subscribe/api/#advanced-features][Pull cached messages @Ntfy-doc]]
** OUTL Dunst Write and Run Script :DUNST:notificationsync:
DEADLINE: <2025-11-27 Thu>
/How to write and run script in =dunst=/
** OUTL Git Automation :GIT:filesync:
/Automate sync process with head repo/
** OUTL Nvim Advanced Configuration :NVIM:nvimconfig:
=neovim= advanced implementations using lua and =lazyvim= configurations structure
*** Lazyvim Plugin Structure
optimal way to place your plugins in =lazyvim=
- /Reference:/ [[https://lazy.folke.io/usage/structuring][Lazyvim Plugin Structure @Lazyvim-blog]]
*** Nvim Reload
How to reload =nvim= without restarting or spawning new instances
- /Reference:/ [[file:/home/whammou/Workspace/nvim-restart/nvim-restart.ai.org][Restart Nvim Function @Gemini]]
** OUTL Running Script File Event :filesync:
DEADLINE: <2025-11-27 Thu>
/Run custom script on file modification event/ \\
/Check-out:/ [[id:c4b5759c-1794-4797-b1ae-adc28bb1aa2a][Nvim Multiple Instances @Org]]
** OUTL Scripting with Rofi :ROFI:
DEADLINE: <2025-11-27 Thu>
:PROPERTIES:
:ID: e88ddffd-71b2-41c2-b1e7-6309f8600812
:END:
/How to write script with =rofi=/
