:PROPERTIES:
:ID: e91e7b0e-dae1-4776-a938-20e59494b887
:END:
#+TITLE: Managing Dotfiles Across Machines
#+OPTIONS: title:t tags:nil todo:nil ^:nil f:t num:t pri:nil toc:t
#+TODO: TODO(t) (e) DOIN(d) PROG(g) PEND(p) OUTL(o) EXPL(x) FDBK(b) WAIT(w) NEXT(n) IDEA(i) | ABRT(a) PRTL(r) RVIW(v) DONE(f)
#+FILETAGS: :topPackages:typDoc:meta:DOTFILES:
* DOIN [#A] Managing Dotfiles with Chezmoi :subChezmoi:
DEADLINE: <2026-02-09 Mon>
:PROPERTIES:
:ID: 58910689-be05-4304-8b9b-7d2c03fee002
:END:
/Configuring dotfiles manager with chezmoi/ \\
/Reference:/
- [[https://www.chezmoi.io/user-guide/frequently-asked-questions/usage/][Chezmoi]]
- [[https://natelandau.com/managing-dotfiles-with-chezmoi/][Managing dotfiles with chezmoi @Blog]]
** Chezmoi Concepts
:PROPERTIES:
:ID: c5fec865-4f66-485f-a22b-189dc25fee2e
:END:

#+BEGIN_QUOTE
Chezmoi computes the target state for the current machine and then updates the destination directory
#+END_QUOTE

- The /destination directory/ is the directory that =chezmoi= manages, usually the home directory, =HOME=
- The /destination state/ is the current state of all the targets in the destination directory
- The /Source state/ declares the desired state of your home directory, including templates that use machine-specific data. It contains only regular files and directories
- The /source directory/ is where =chezmoi= stores the source state. By default it is =HOME/.local/share/chezmoi=
- The /config file/ contains machine specific data. By default it is =HOME/.config/chezmoi/chezmoi.toml=
- The /target state/ is the desired state of the destination directory. It is computed from the source state, the config file, and the destination state. The target state includes regular files and directories, and may also include symbolic links, script to be run, and targets to be removed
- The /working tree/ is the git working tree. Normally it is the same as the source directory, but an be a parent of the source directory
*** OUTL Managing Outside of HOME
:PROPERTIES:
:ID: 6c8020bc-3705-4f3d-b4c6-053c19f14b76
:END:

/Managing files that live outside of the/ =HOME= /dir/ \\
/Reference:/  [[https://www.chezmoi.io/user-guide/frequently-asked-questions/design/#can-i-use-chezmoi-to-manage-files-outside-my-home-directory][Manage Files outside of HOME @Doc]]
*** Manage Machine-to-Machine Differences
:PROPERTIES:
:ID: 4fdaa869-576b-4ef3-8249-25c7e78f66bf
:END:

#+BEGIN_QUOTE
My primary goal of using =chezmoi= is to be able to manage config files across multiple machines. I want to keep much configuration the same across these machines, but also need machine-specific configurations for emails address and credentials. Chezmoi achieves this by using =text/template= for the source state where needed
#+END_QUOTE
**** Chezmoi Template
:PROPERTIES:
:ID: f7099a94-12b3-4ee1-abd6-ae6036d9d74d
:END:

#+BEGIN_QUOTE
Templates are used to change the contents of a file depending on the environment. For Example, using hostname of the machine to create different configuations of different machines
#+END_QUOTE

When reading files from the /source state/, =chezmoi= interprets them as a template if either the following is true:
- The file name has =.tmpl= suffix
- The file is in the =.chezmoitemplate= directory, or sub-directory \\
  
For example, Home =HOME/.gitconfig= on the personal machine might look like:
#+BEGIN_SRC toml
[user]
  email = "me@home.org"
#+END_SRC

Whereas on a work machine, it might be:
#+BEGIN_SRC toml
[user]
  email = "firstname.lastname@company.com"
#+END_SRC

/Reference:/  [[https://www.chezmoi.io/user-guide/templating/#template-data][Chezmoi templating @Doc]]
***** Create a Template
:PROPERTIES:
:ID: 87e04cec-9432-44a0-bb88-04371aca78c6
:END:

To handle this, on each machine create a configuration file called =HOME/.config/chezmoi.toml= defining variables that might vary from machine to machine e.g. the home machine
#+BEGIN_SRC toml
[data]
  email = "me@home.org"
#+END_SRC

#+BEGIN_QUOTE org
[!TIP]
If you intended to store private data /(e.g. access token)/ in =HOME/.config/chezmoi/chezmoi.toml=, make sure it has permission =0600=. Variable names must start a letter and be followed by zero or more letters or digits
#+END_QUOTE

Then, add =HOME/.gitconfig= to chezmoi using the =--template= flag to turn it into a template:

#+BEGIN_SRC sh
chezmoi add --template ~/.config/
#+END_SRC
***** Edit a Template
:PROPERTIES:
:ID: 30772298-6704-488b-8c39-f70c84fb3eb7
:END:

Open the template (which will be saved in the =HOME/.local/share/chezmoi/dot_gitconfig.tmp= ):
#+BEGIN_SRC bash
chezmoi edit ~/.gitconfig
#+END_SRC

Edit the file so it looks like:
#+BEGIN_SRC tmpl
[user]
  email = {{.email | quote}}
#+END_SRC

#+BEGIN_QUOTE org
[!TIP]
For a full list of variable, run: =chezmoi data=
#+END_QUOTE

**** Interacting with Password-Managers
:PROPERTIES:
:ID: 391def47-e522-4a6e-b1ff-a829cb472206
:END:

#+BEGIN_QUOTE org
[!NOTE]
Chezmoi support functions to interact with password managers
#+END_QUOTE

Some password managers allow you to store complete files. The files can be retrieved with chezmoi's template functions. For example, if you have a file stored in =1Password= with the UUID =uuid= then you can retrieve it with the template

#+BEGIN_SRC tmpl
{{- onepasswordDocument "uuid" -}}
#+END_SRC

The =-= inside the brackets remove any whitespace before or after the template expression, which is useful if your editor has added any newlines \\

#+BEGIN_QUOTE org
[!WARNING]
If, after executing the template, the file contents are empty, the target file will be removed. This can be used to ensure that files are only present on certain machines. If you want an empty file to be created anyway, you will need to five an =empty_= prefix
#+END_QUOTE

/Visit:/  [[id:0f64b514-3287-45bc-af26-363516cb076e][Password Manager Integration @Org]]
**** Ignore Files on Different Machines
:PROPERTIES:
:ID: 3fa1eb5a-c00c-4535-ba40-2d3236dc36fe
:END:

#+BEGIN_QUOTE
For coarser-gained control of files and entire directories managed on different machines, or to exclide certain files completely, you can create =.chezmoiignore= files in the source director.
#+END_QUOTE

Specify a list of pattern that chezmoi should ignore, and are interpreted as templates

#+BEGIN_SRC gitignore
README.md
{{- if ne .chezmoi.hostname "work-laptop" }}
.work # only manage .work on work-laptop
{{- end }}
#+END_SRC

#+BEGIN_QUOTE org
[!NOTE]
The use of =ne= /(not equal)/ is deliberate. What we want to achieve is "only install =.work= if hostname is =work-laptop=. But chezmoi installs everything by default, so we have to turn the logic around an instead write "ignore =.work= unless the hostname is =work-laptop="
#+END_QUOTE

/Reference:/  [[https://www.chezmoi.io/user-guide/manage-machine-to-machine-differences/#use-templates][Ignore files on different machines @Doc]]
*** OUTL Password Manager Integration
:PROPERTIES:
:ID: 0f64b514-3287-45bc-af26-363516cb076e
:END:
/Reference:/  [[https://www.chezmoi.io/user-guide/password-managers/][Chezmoi password manager integration @Doc]]
