:PROPERTIES:
:ID: e91e7b0e-dae1-4776-a938-20e59494b887
:END:
#+TITLE: Managing Dotfiles Across Machines

#+OPTIONS: title:nil tags:nil todo:nil ^:nil f:t num:t pri:nil toc:t
#+LATEX_HEADER: \renewcommand\maketitle{} \usepackage[scaled]{helvet} \renewcommand\familydefault{\sfdefault}
#+TODO: TODO(t) (e) DOING(d) PEND(p) OUTL(o) RESEARCH(s) FEEDBACK(b) WAITING(w) NEXT(n) | IDEA(i) ABORTED(a) PARTIAL(r) REVIEW(v) DONE(f)
#+FILETAGS: :DOC:META:DOTFILES:
#+HTML:<details>

* Managing Dotfiles Across Machines :DOC:META:DOTFILES:
#+HTML:</details>
** DOIN Managing Dotfiles with Chezmoi :CHEZMOI:
DEADLINE: <2026-02-05 Thu>
:PROPERTIES:
:ID: 58910689-be05-4304-8b9b-7d2c03fee002
:END:
/Configuring dotfiles manager with chezmoi/ \\
/Reference:/
- [[https://www.chezmoi.io/user-guide/frequently-asked-questions/usage/][Chezmoi]]
- [[https://natelandau.com/managing-dotfiles-with-chezmoi/][Managing dotfiles with chezmoi @Blog]]
*** Chezmoi Concepts
#+BEGIN_QUOTE
Chezmoi computes the target state for the current machine and then updates the destination directory
#+END_QUOTE

- The /destination directory/ is the directory that =chezmoi= manages, usually the home directory, =~=
- The /destination state/ is the current state of all the targets in the destination directory
- The /Source state/ declares the desired state of your home directory, including templates that use machine-specific data. It contains only regular files and directories
- The /source directory/ is where =chezmoi= stores the source state. By default it is =~/.local/share/chezmoi=
- The /config file/ contains machine specific data. By default it is =~/.config/chezmoi/chezmoi.toml=
- The /target state/ is the desired state of the destination directory. It is computed from the source state, the config file, and the destination state. The target state includes regular files and directories, and may also include symbolic links, script to be run, and targets to be removed
- The /working tree/ is the git working tree. Normally it is the same as the source directory, but an be a parent of the source directory
**** OUTL Managing Outside of HOME
/Managing files that live outside of the/ =HOME= /dir/ \\
/Reference:/  [[https://www.chezmoi.io/user-guide/frequently-asked-questions/design/#can-i-use-chezmoi-to-manage-files-outside-my-home-directory][Manage Files outside of HOME @Doc]]
**** Manage Machine-to-Machine Differences
#+BEGIN_QUOTE
My primary goal of using =chezmoi= is to be able to manage config files across multiple machines. I want to keep much configuration the same across these machines, but also need machine-specific configurations for emails address and credentials. Chezmoi achieves this by using =text/template= for the source state where needed
#+END_QUOTE
***** Chezmoi Template

#+BEGIN_QUOTE
Templates are used to change the contents of a file depending on the environment. For Example, using hostname of the machine to create different configuations of different machines
#+END_QUOTE

When reading files from the /source state/, =chezmoi= interprets them as a template if either the following is true:
- The file name has =.tmpl= suffix
- The file is in the =.chezmoitemplate= directory, or sub-directory \\
  
For example, Home =~/.gitconfig= on the personal machine might look like:
#+BEGIN_SRC toml
[user]
  email = "me@home.org"
#+END_SRC

Whereas on a work machine, it might be:
#+BEGIN_SRC toml
[user]
  email = "firstname.lastname@company.com"
#+END_SRC

/Reference:/  [[https://www.chezmoi.io/user-guide/templating/#template-data][Chezmoi templating @Doc]]
****** Create a Template
To handle this, on each machine create a configuration file called =~/.config/chezmoi.toml= defining variables that might vary from machine to machine e.g. the home machine
#+BEGIN_SRC toml
[data]
  email = "me@home.org"
#+END_SRC

#+BEGIN_QUOTE markdown
[!TIP]
If you intended to store private data /(e.g. access token)/ in =~/.config/chezmoi/chezmoi.toml=, make sure it has permission =0600=. Variable names must start a letter and be followed by zero or more letters or digits
#+END_QUOTE

Then, add =~/.gitconfig= to chezmoi using the =--template= flag to turn it into a template:

#+BEGIN_SRC sh
chezmoi add --template ~/.config/
#+END_SRC
****** Edit a Template
Open the template /(which will be saved in the/ =~/.local/share/chezmoi/dot_gitconfig.tmp= /)/:
#+BEGIN_SRC bash
chezmoi edit ~/.gitconfig
#+END_SRC

Edit the file so it looks like:
#+BEGIN_SRC tmpl
[user]
  email = {{.email | quote}}
#+END_SRC

#+BEGIN_QUOTE markdown
[!TIP]
For a full list of variable, run: =chezmoi data=
#+END_QUOTE

***** OUTL Interacting with Password-Managers

#+BEGIN_QUOTE markdown
[!NOTE]
Chezmoi support functions to interact with password managers
#+END_QUOTE


***** Ignore Files on Different Machines
#+BEGIN_QUOTE
For coarser-gained control of files and entire directories managed on different machines, or to exclide certain files completely, you can create =.chezmoiignore= files in the source director.
#+END_QUOTE

Specify a list of pattern that chezmoi should ignore, and are interpreted as templates

#+BEGIN_SRC tmpl
README.md
{{- if ne .chezmoi.hostname "work-laptop" }}
.work # only manage .work on work-laptop
{{- end }}
#+END_SRC

#+BEGIN_QUOTE markdown
[!NOTE]
The use of =ne= /(not equal)/ is deliberate. What we want to achieve is "only install =.work= if hostname is =work-laptop=. But chezmoi installs everything by default, so we have to turn the logic around an instead write "ignore =.work= unless the hostname is =work-laptop="
#+END_QUOTE

/Reference:/  [[https://www.chezmoi.io/user-guide/manage-machine-to-machine-differences/#use-templates][Ignore files on different machines @Doc]]
**** Password Manager Integration
:PROPERTIES:
:ID: 0f64b514-3287-45bc-af26-363516cb076e
:END:
